---    
- name: Create a darkplaces container
  docker_container:
    name: darkplaces
    image: nijlunsing/quake1-armhf
    state: started
    pull: yes
    ports: 
      - "26000:26000/udp"   
      
- name: Wait for 3 seconds
  pause: seconds=3

- name: Test if container is running
  shell: docker inspect -f {{ '{{' }}.State.Running{{ '}}' }} darkplaces
  register: container_result
  failed_when: "'false' in container_result.stdout"