---
- name: Create a openvpn container
  docker_container:
    name: openvpn
    image: nijlunsing/openvpn-armhf
    state: started
    privileged: yes
    pull: yes
    volumes:
      - "/mnt/internal/volumes/openvpn:/etc/openvpn"
    ports: 
      - "1194:1194/udp"   

- name: Wait for 3 seconds
  pause: seconds=3

- name: Test if container is running
  shell: docker inspect -f {{ '{{' }}.State.Running{{ '}}' }} watchtower
