---
- name: Create a OpenHab container
  docker_container:
    name: openhab
    image: nijlunsing/openhab-armhf
    state: started
    pull: yes
    volumes:
      - "/mnt/internal/volumes/openhab:/etc/openhab"
    ports: 
      - "8080:8080"

- name: Test Openhab port
  wait_for:
    port: 8080