---  
- name: Essentials (Git,software-properties-common )
  apt: name={{item}} state=installed
  with_items:
       - git
       - software-properties-common
       - dos2unix

- name: Install Ansible
  apt:
    update_cache: yes
    name: ansible
       
- name: Create a jenkins container
  docker_container:
    name: jenkins
    image: nijlunsing/jenkins-armhf
    state: started
    pull: yes
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/opt/var/jenkins_home:/var/jenkins_home"
      - "/etc/ansible:/etc/ansible"
    ports: 
      - "8080:8080"   

- name: Test Jenkins port
  wait_for:
    port: 8080
    
- name: Create a watchtower container
  docker_container:
    name: watchtower
    image: v2tec/watchtower:armhf-latest
    state: started
    pull: yes
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

- name: add user to docker group
  user:
    name: user 
    shell: /bin/bash
    groups: docker
    append: yes
