---  
- name: Create a dpmaster container
  docker_container:
    name: dpmaster
    image: nijlunsing/dpmaster-armhf
    state: started
    ports: 
      - "27950:27950"
      
- name: Wait for 3 seconds
  pause: seconds=3

- name: Test if container is running
  shell: docker inspect -f {{ '{{' }}.State.Running{{ '}}' }} dpmaster
  register: container_result
  failed_when: "'false' in container_result.stdout"